# Generated by Django 3.1.1 on 2020-09-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200917_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
