# Generated by Django 3.1.1 on 2020-09-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.TextField(default='', max_length=300),
        ),
    ]
