# Generated by Django 3.1.1 on 2020-09-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200920_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
